config/routes.rb
Rails.application.routes.draw do

  get 'empleados/new'

  get 'empleados/edit'

  root 'empresas#show'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/signup' => 'empresas#new'
  post '/signup' => 'empresas#create'
  resources :empresas
  resources :sucursals
  resources :empleados

end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
	validates :nombre, :rfc, :sucursal_id, :presence => true
	belongs_to :sucursal
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
	validates :nombre_persona, :correo, :rfc, :nombre_empresa, :password_digest, :presence => true
	has_many :sucursals
	has_secure_password

	def listar_sucursales
		Sucursal.where(empresa_id: self.id)
	end

	def Empresa.digest(string)
	  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
	                                                BCrypt::Engine.cost
	  BCrypt::Password.create(string, cost: cost)
	end
end

app/models/sucursal.rb
class Sucursal < ActiveRecord::Base
	validates :nombre, :empresa_id, :presence => true
	belongs_to :empresa
	has_many :empleados
	accepts_nested_attributes_for :empleados, allow_destroy: true, reject_if: proc { |attributes| attributes[:nombre].blank? || attributes[:rfc].blank? || attributes[:empresa_id].blank? }

	def listar_empleados
		Empleado.where(sucursal_id: self.id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_empresa
  	@current_empresa ||= Empresa.find(session[:empresa_id]) if session[:empresa_id]
  end
  helper_method :current_empresa

  def authorize
  	redirect_to '/login' unless current_empresa
  end

end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  before_filter :authorize
  def new
  	@empleado = Empleado.new
  	@lista_sucursales = current_empresa.listar_sucursales
  end

  def create
  	@empleado = Empleado.new(empleado_params)
  	if @empleado.save
  		redirect_to edit_sucursal_path(@empleado.sucursal_id)
  	else
  		@empleado = Empleado.new
  		@lista_sucursales = current_empresa.listar_sucursales
  		render 'new'
  	end
  end

  def edit
  	@empleado = Empleado.find(params[:id])
  	@lista_sucursales = current_empresa.listar_sucursales
  end

  def update
	  @empleado = Empleado.find(params[:id])
	 
	  if @empleado.update(empleado_params)
	    redirect_to edit_sucursal_path(Sucursal.find(@empleado.sucursal_id))
	  else
	  	@empleado = Empleado.find(params[:id])
	  	@lista_sucursales = current_empresa.listar_sucursales
	    render 'edit'
	  end
	end

	def destroy
		@empleado = Empleado.find(params[:id])
		sucursal = Sucursal.find(@empleado.sucursal_id)
		@empleado.destroy

		redirect_to edit_sucursal_path(sucursal)
	end

	private
		def empleado_params
		  params.require(:empleado).permit(:nombre, :rfc, :puesto, :sucursal_id)
		end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_filter :authorize, only: [:show]
  def new
  	@empresa = Empresa.new
  end

  def create
  	@empresa = Empresa.new(empresa_params)
  	if @empresa.save
  		redirect_to :controller => 'sessions', :action => 'new'
  	else
  		render 'new'
  	end
  end

  def show
    @lista_sucursales = current_empresa.listar_sucursales
  end

  private
  	def empresa_params
  		params.require(:empresa).permit(:nombre_persona, :correo, :rfc, :nombre_empresa, :password, :password_confirmation)  		
  	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		empresa = Empresa.find_by_correo(params[:correo])
		if empresa && empresa.authenticate(params[:password])
			session[:empresa_id] = empresa.id
			redirect_to empresa
		else
			@error = "Combinacion de correo/password incorrectos"
			render 'new'
		end
	end

	def destroy
		session[:empresa_id] = nil
		redirect_to '/login'
	end
end

app/controllers/sucursals_controller.rb
class SucursalsController < ApplicationController
	before_filter :authorize
	def new
		@sucursal = Sucursal.new
	end

	def create
		empleados = sucursal_params[:empleados_attributes]
		@sucursal = Sucursal.new(sucursal_params)
  	@sucursal[:empresa_id] = current_empresa.id
  	if @sucursal.save
	  	if empleados.present?
	  		empleados.each do |emp|
	  			#los atributos vienen en un arreglo ["0", {"nombre"=>"", "rfc"=>"", "puesto"=>""}]
		  		emp = emp.last
	  			if !emp.include?(:_destroy)
		  			emp[:sucursal_id] = @sucursal.id
	  				@empleado = Empleado.new(emp)
	  				if !@empleado.save
	  					render 'new' and return
	  				end
	  			end
	  		end
	  	end	  	
  		redirect_to root_path
  	else
  		render 'new'
  	end
	end

	def edit
		@sucursal = Sucursal.find(params[:id])
		@lista_empleados = @sucursal.listar_empleados
	end

	def update
		@sucursal = Sucursal.find(params[:id])
		if @sucursal.update(sucursal_params)
		  redirect_to root_path
		else
		  render 'edit'
		end
	end

	def destroy
		@sucursal = Sucursal.find(params[:id])
		@sucursal.destroy

		redirect_to root_path
	end

	private
		def sucursal_params
			params.require(:sucursal).permit(:nombre, :colonia, :numero_ext, :numero_int, :codigo_postal, :ciudad, :pais, empleados_attributes:[:nombre, :rfc, :puesto, :id, :_destroy])
			
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/sucursals_helper.rb
module SucursalsHelper
end

app/views/empleados/edit.html.erb
<%= form_for @empleado do |f| -%>
	<p>
			<%= f.label :nombre %><br>
			<%= f.text_field :nombre %>
		</p>

		<p>
			<%= f.label :rfc %><br>
			<%= f.text_field :rfc, :disabled => true %>
		</p>

		<p>
			<%= f.label :puesto %><br>
			<%= f.text_field :puesto %>
		</p>

		<p>
			<%= collection_select(:empleado, :sucursal_id, @lista_sucursales, :id, :nombre) %>
		</p>

		<p>
			<%= f.submit "Actualizar", class: 'btn btn-info', :id => "editar-empleado" %>
		</p>
<% end %>

app/views/empleados/new.html.erb
<h1>Registro de Empleado</h1>
<%= form_for @empleado do |f| -%>
	<p>
			<%= f.label :nombre %><br>
			<%= f.text_field :nombre %>
		</p>

		<p>
			<%= f.label :rfc %><br>
			<%= f.text_field :rfc, class: "disabled" %>
		</p>

		<p>
			<%= f.label :puesto %><br>
			<%= f.text_field :puesto %>
		</p>

		<p>
			<%= collection_select(:empleado, :sucursal_id, @lista_sucursales, :id, :nombre) %>
		</p>

		<p>
			<%= f.submit "Registrar", class: 'btn btn-info', :id => "registrar-empleado" %>
		</p>
<% end %>

app/views/empresas/new.html.erb
<h1>Registro de Empresa</h1>
<%= form_for @empresa do |f| %>
	<p>
		<%= f.label :nombre_persona %><br>
		<%= f.text_field :nombre_persona %>
	</p>

	<p>
		<%= f.label :correo %><br>
		<%= f.text_field :correo %>
	</p>

	<p>
		<%= f.label :rfc %><br>
		<%= f.text_field :rfc %>
	</p>

	<p>
		<%= f.label :nombre_empresa %><br>
		<%= f.text_field :nombre_empresa %>
	</p>

	<p>
		<%= f.label :password %><br>
		<%= f.password_field :password %>
	</p>

	<p>
		<%= f.label :password_confirmation %><br>
		<%= f.password_field :password_confirmation %>
	</p>

		<p>
			<%= f.submit "Registrar", :id => "registrar" %>
		</p>
<% end %>

app/views/empresas/show.html.erb
<% if @lista_sucursales.blank? %>
	<h1>No hay sucursales registradas para esta empresa</h1>
	<%= link_to "Registrar Sucursal", new_sucursal_path %>
<% else %>
		<table class="table table-bordered table-hover">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Cantidad Empleados</th>
					<th colspan="2">Editar</th>
				</tr>
			</thead>
			<tbody>
				<% @lista_sucursales.each do |sucursal| %>
					<tr>
						<td> <%= sucursal.nombre %> </td>
						<td> <% empleados = sucursal.listar_empleados %>
								<%= empleados.count %>
						</td>
						<td><%= link_to "Actualizar información", edit_sucursal_path(sucursal) %></td>
						<td> <%= link_to "Borrar", sucursal_path(sucursal), method: :delete %></td>
					</tr>
				<% end %>		
			</tbody>
		</table>
		
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prueba Empresas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse" style="position: relative;">
      <% if current_empresa %>
            <%= link_to "#{current_empresa.nombre_empresa}", root_path, class: "navbar-brand"%>   
      <% else %>
        <%= link_to "Sistema de empresas", root_path, class: "navbar-brand"%> 
      <% end %>
      <div class="container">        
        <nav>          
          <ul class="nav navbar-nav navbar-right">
            <% if current_empresa %>
            	<li><%= link_to "Registrar Sucursal",   new_sucursal_path %></li>
            	<li><%= link_to "Registrar Empleados", new_empleado_path %></li>
            	<li><%= link_to "Logout", '/logout' %></li>
            <% else %>
            	<li><%= link_to "Login",   login_path %></li>
            	<li><%= link_to "Registro", new_empresa_path %></li>
            <% end %>
            
          </ul>
        </nav>
      </div>
    </header>
<div id="mensajes"></div>
<%= yield %>
<%= insert_paloma_hook %>
<script type="text/javascript">
  $(document).ready(function(){
      Paloma.start();
  });
</script>
</body>
</html>

app/views/sucursals/edit.html.erb
<h1>Actualizar Sucursal</h1>
<%= form_for @sucursal do |f| %>
	<p>
		<%= f.label :nombre %><br>
		<%= f.text_field :nombre %>
	</p>

	<p>
		<%= f.label :calle %><br>
		<%= f.text_field :calle %>
	</p>

	<p>
		<%= f.label :colonia %><br>
		<%= f.text_field :colonia %>
	</p>

	<p>
		<%= f.label :numero_ext %><br>
		<%= f.text_field :numero_ext %>
	</p>

	<p>
		<%= f.label :numero_int %><br>
		<%= f.text_field :numero_int %>
	</p>

	<p>
		<%= f.label :codigo_postal %><br>
		<%= f.text_field :codigo_postal %>
	</p>

	<p>
		<%= f.label :ciudad %><br>
		<%= f.text_field :ciudad %>
	</p>

	<p>
		<%= f.label :pais %><br>
		<%= f.text_field :pais %>
	</p>

	<br>
	<br>
		<p>
			<%= f.submit "Actualizar", class: 'btn btn-info', :id => "editar-sucursal" %>
		</p>
<% end %>

<% if @lista_empleados.present? %>
	<h1>Empleados de sucursal <%= @sucursal.nombre %></h1>	
	<table class="table table-bordered table-hover">
		<thead>
			<tr>
				<th>Nombre</th>
				<th>RFC</th>
				<th>Puesto</th>
				<th colspan="2">Editar</th>
			</tr>
			<% @lista_empleados.each do |empleado| %>
				<tr>
					<td><%= empleado.nombre %></td>
					<td><%= empleado.rfc %></td>
					<td><%= empleado.puesto %></td>
					<td><%= link_to "Actualizar información", edit_empleado_path(empleado) %></td>
					<td> <%= link_to "Borrar Empleado", empleado_path(empleado), method: :delete %></td>
				</tr>
			<% end %>
		</thead>
	</table>
<% else %>
	
<% end %>

app/views/sucursals/new.html.erb
<h1>Registro de Sucursal</h1>
<%= form_for @sucursal do |f| %>
	<p>
		<%= f.label :nombre %><br>
		<%= f.text_field :nombre %>
	</p>

	<p>
		<%= f.label :calle %><br>
		<%= f.text_field :calle %>
	</p>

	<p>
		<%= f.label :colonia %><br>
		<%= f.text_field :colonia %>
	</p>

	<p>
		<%= f.label :numero_ext %><br>
		<%= f.text_field :numero_ext %>
	</p>

	<p>
		<%= f.label :numero_int %><br>
		<%= f.text_field :numero_int %>
	</p>

	<p>
		<%= f.label :codigo_postal %><br>
		<%= f.text_field :codigo_postal %>
	</p>

	<p>
		<%= f.label :ciudad %><br>
		<%= f.text_field :ciudad %>
	</p>

	<p>
		<%= f.label :pais %><br>
		<%= f.text_field :pais %>
	</p>

	<%= f.nested_fields_for :empleados do |ff| %>
		<%= ff.remove_nested_fields_link 'Quitar empleado', class: 'btn btn-danger' %>
		<p>
			<%= ff.label :nombre %><br>
			<%= ff.text_field :nombre, class: "input-empleados-nombre" %>
		</p>

		<p>
			<%= ff.label :rfc %><br>
			<%= ff.text_field :rfc, class: "input-empleados-rfc" %>
		</p>

		<p>
			<%= ff.label :puesto %><br>
			<%= ff.text_field :puesto %>
		</p>
	<% end %>
	<%= f.add_nested_fields_link :empleados, 'Agregar empleado', class: 'btn btn-primary', id: 'add-empleado' %>
	<br>
	<br>
		<p>
			<%= f.submit "Registrar", class: 'btn btn-info', :id => "registrar" %>
		</p>
<% end %>